### ISSUE TITLE
HTTPS issues

### ISSUE THREAD

**Issue by Larsene** [pierre-alain-b/rainloop-nextcloud#117]
Hello, 

There's a config problem on rainloop, installed on a secured Nextcloud installation.

Loading or displaying an image is not secured 

![RAINLOOP](https://user-images.githubusercontent.com/8544729/68461048-a0906400-0209-11ea-9225-b2d3b134e0aa.jpg)

**Comment by pierre-alain-b** [comment]
I have no such issue here. Can you give more information?
It seems rather to be a configuration of the hosting.

**Comment by pierre-alain-b** [comment]
Are you sure it is not an image embedded in an HTML email referring to a non HTTPS site? If this is the case, Rainloop could unfortunately not do anything, you should ask the email sender to use HTTPS for images or should you not open images (this is why by default images are not opened by webmails, because opening images gives away (potentially) the information that you read the message.
