### ISSUE TITLE
Username for the Administrator Panel

### ISSUE THREAD

**Issue by Valdnet** [pierre-alain-b/rainloop-nextcloud#163]
The admin panel username should not be case sensitive by Rainloop.
Currently, I had a case that I set the login name with a capital letter and entered with a lower case letter.

The NC is not case-sensitive in the login name.

**Comment by nkinkade** [comment]
@Valdnet: This isn't really my issue, but I just noticed this one and thought I would give my input, for what it's worth. I respectfully disagree with you here. In my view, not respecting case would be a mistake.  In my mind, there is a huge difference between `UsErNaMe` and `username`. Indeed, `U` and `u` have totally different character codes. To ignore case would mean that underlying character codes means nothing, and that the application should make assumptions about what the user intended. It is also a possible security issues, as it makes guessing usernames a little easier.

I am actually shocked that NC logins are not case sensitive. Searching for something like "nextcloud login case sensitive" brings up a number of issues and help threads with people asking for it to become case sensitive.

**Comment by Valdnet** [comment]
@nkinkade I agree with you, but it can be confusing to other NC users. I experienced it myself :wink:.

**Comment by nkinkade** [comment]
I see your point, but I think it would be a mistake to perpetuate what is, in my view, a bad model. :)

**Comment by pierre-alain-b** [comment]
Well, tricky issue.
I recommend not to change because it could break the settings of some users. If I agree with @nkinkade this is not a good model, it is however a bit complex because how can you make sure users will not be confused when sharing a document to Nkinkade or nkinkade or nKinkade... would prove a good way to steal documents! So I recognize the limitation of NC has some merits when the username is used for identification/sharing purpose.

In the case of Rainloop admin, I propose to respect and keep the default settings of Rainloop which is to be case sensitive.
