### ISSUE TITLE
auto login fail with nc19rc2 and rl 7.0 beta

### ISSUE THREAD

**Issue by Antoine26220** [pierre-alain-b/rainloop-nextcloud#164]
I am unable to log automatically to rainloop.

my working config:
use shot login => off
default domain => null
when i use my "username@domain.tld" to connect it works but not automatically.

When i try to set default domain to my domain and short login i can't connect at all!

hope it will help...

**Comment by pierre-alain-b** [comment]
Was it working differently with the previous version?

What does your mail server expect? A short login or the long login?
If it works with short_login == off, then I assume your mail server wants the long login, no?

**Comment by Antoine26220** [comment]
With the previous version i just log in to nextcloud and it pass my credentials to rainloop.
I configured nextcloud to pass my complete email to rainloop 
Now i have to entrer my credentials in rainloop afer login to nextcloud.

My server expects a long login and nextcloud is configure to pass my email and password to rainloop in genral settings but it doesn't work.

i also tried to set directly my username@domain.tld and password 
in the personal setting and it works. I mean it connect directly to rainloop without asking login informations.
But, i try to do it with non admin account and it doesn't work (error). So i add this non admin user to the admin account and it was possible to save its credentials. I delete this account from admin group after that and the credentials i save stay and the autologin works.

I hope my explanations are understandable...

**Comment by nkinkade** [comment]
I believe I'm seeing the same thing, and the problem likely has something to do with my App Framework changes, not NC 19. I'll dig into it, unless someone beats me to it.

**Comment by pierre-alain-b** [comment]
Ok I will need to some tests as well!

**Comment by pierre-alain-b** [comment]
I do replicate and in fact the error message is quite explicit in the JSON: it says Error 403 =>
"Logged in user must be an admin"

**Comment by pierre-alain-b** [comment]
I think this is where the verification takes place. Now we need to find the way to tell NC to accept the personal settings page as not admin-level.
https://github.com/nextcloud/server/blob/1762a409f954fd9a66e7572704ea9ba7813601b4/lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php#L153

**Comment by pierre-alain-b** [comment]
The documentation says this:

> To turn off checks the following Annotations can be added before the controller:
> 
>     @NoAdminRequired: Also users that are not admins can access the page
>     @NoCSRFRequired: Don’t check the CSRF token (use this wisely since you might create a security hole; to understand what it does see Security guidelines)
>     @PublicPage: Everyone can access the page without having to log in
> 
> A controller method that turns off all checks would look like this:

**Comment by pierre-alain-b** [comment]
I am releasing beta 2 so that you can test!

**Comment by pierre-alain-b** [comment]
Beta2 is available here: https://github.com/pierre-alain-b/rainloop-nextcloud/releases/download/7.0.0-beta-2/rainloop.tar.gz

I cannot publish on the Nextcloud apps store that seems down for now but I think you can test fairly easily by using the above release. Let us know!

**Comment by nkinkade** [comment]
Oh, good find, @pierre-alain-b! I will test with Beta2 this evening. Thank you.

**Comment by nkinkade** [comment]
Beta2 seems to resolve this issue for me.

**Comment by Antoine26220** [comment]
The admin access to set mail and password for user is OK for me too.

I still have a problem with nextcloud not automatically passing credentials when the option is active in the general setting.
![Nouvelle image bitmap](https://user-images.githubusercontent.com/64309327/82404471-ae992a00-9a61-11ea-8e65-8d97e9182fc2.jpg)

**Comment by pierre-alain-b** [comment]
Hi Antoine,
To understand that one, can you confirm that an email is set for the users in their user account? And there is no user-defined credentials in the personal settings that would supersede the setting?

**Comment by Antoine26220** [comment]
There is a valid email set in "personal info" and to test this function i delete the credentials in the "Personal" "additional settings" section.

**Comment by pierre-alain-b** [comment]
@piti-diablotin if I remember well, you developed these functions! I must say I am not sure how they work and where the password is supposed to come from when one selects "Automatically login with Nextcloud user email credentials or user defined credentials". What I understand is that the login is taken from the email set in the nextcloud user account but what about the password?

Would you have a few minutes to have a look and help us?

**Comment by nkinkade** [comment]
When I was testing this last night I found that auto-login using user-set credentials (in Setttings->Personal->Additional settings) did not work until I went to RainLoop admin settings and configured a "Default Domain" under the "Login" section. To verify that RainLoop was actually using the credentials I had stored in Personal Settings, I modified the password to something incorrect and verified that auto-login failed. I then set the password to the right one, and verified that auto-login worked as expected.

@Antoine26220, by any chance is "Default Domain" under the Login section in the RainLoop admin settings (not NC Additional Settings) unset?

**Comment by Antoine26220** [comment]
It's a settings combination i didn't try and you're right it works!

**Comment by pierre-alain-b** [comment]
OK I am closing the issue but I think I need some kind of explanation. Shall we fix the explanations somehow to ease use by others?

**Comment by nkinkade** [comment]
I suspect, though can't presently confirm, that the "Default Domain" setting under "Login" in the RainLoop admin area may only be necessary if the user has the "short login" option enabled (which I do). When "short login" is enabled for the IMAP and SNMP server, RainLoop will have no way of knowing which domain to login to. Without "short login" the default domain is implied in the full email address.

@Antoine26220: Can you confirm whether you are using the "short login" option?

On a related note, I do think we need to update the text for the various options for auto-login in the Admin->Additional Settings area. To me, they are confusing. I'll submit a PR with some proposed changes.

**Comment by pierre-alain-b** [comment]
What you say makes sense.

The explanations of the different options have already been tweaked multiple times but happy to see another try! We will then need to update all translations files but we will make it if you think a new wording is worth it.

By the way, beta-4 is out.

I am tempted to publish 7.0 to have more people with NC 19 beta test. Because I am not sure many people test the nightly releases.

Would you veto a release of our work so far?

**Comment by nkinkade** [comment]
I don't know much (really anything) about how new versions of apps are published in the NC app store. If you released 7.0, would it only apply to people running some version of NC19? That is, people running NC18 would not be notified of an app update? If that is true, then I see no harm in releasing 7.0. All of my testing with beta{1,2,3} is successful so far, plus I'm running the changes you published in beta4 and I haven't seen any issues yet.

I see your point about modifying those strings. But presumably you could immediately update the French translations :), and @Valdnet is super active in translating to Polish, and I see that a Russian translation was just added yesterday.

I'll take stab at updating the strings. If you don't like or disagree with my suggestions, easy enough to just reject/close my PR. :)

Oh, one other question: If the admin has configure RainLoop to always try to login using the user's NC credentials, should the RainLoop email and password form not be displayed in the Personal->AdditionalSettings? Should those fields only be shown if the admin selects to allow the users to auto-login by entering email/password in personal settings?

**Comment by pierre-alain-b** [comment]
- Yes the 7.0 version is set to be only proposed to NC19 users, not for NC18 and below. It will stay this way as we have made multiple changes that would not work for NC18 and below.
- Yes I guess @Valdnet and I will be pretty quick to update our respective files :-)
- OK I will wait for your rephrasing attempt before publishing 7.0
- On the last point, no it should not be hidden: the options say that it uses the default setting OR the user setting if there is one set. Many users complained when it was not the case: namely when the admin has set something that could not be overriden by the user setting. I would recommend to keep it that way.

**Comment by Antoine26220** [comment]
> 
> 
> I suspect, though can't presently confirm, that the "Default Domain" setting under "Login" in the RainLoop admin area may only be necessary if the user has the "short login" option enabled (which I do). When "short login" is enabled for the IMAP and SNMP server, RainLoop will have no way of knowing which domain to login to. Without "short login" the default domain is implied in the full email address.
> 
> @Antoine26220: Can you confirm whether you are using the "short login" option?
> 
> On a related note, I do think we need to update the text for the various options for auto-login in the Admin->Additional Settings area. To me, they are confusing. I'll submit a PR with some proposed changes.

No i don't use short login!

For now the only way i get it to work is with long login, default domain set to my domain and "Automatically login with Nextcloud user credentials or user defined credentials "

I 'm not sure i 've tested every combination but it's the only way i can connect automatically without enter the credentials for each users settings.

Sorry i realise i'm still in beta 2, i install beta 4 right now!

**Comment by nkinkade** [comment]
@pierre-alain-b: I'm now a little confused by the existing three options. Let me explain what I think they are supposed to mean (not how they are actually working in the code), and you can correct me?

### Let the user define its own email/password credentials only 

#### What I think this is _supposed_ to mean
RainLoop will **not** attempt to auto-login using the user's NC credentials, but will **only** attempt to auto-login if the user sets a user/password on their personal settings page.

#### How it is _actually_ working in the current code
The code is current working as described above.

### Automatically login with Nextcloud user credentials or user defined credentials 

#### What I think this is _supposed_ to mean
If the user has set a RainLoop user/password in their personal settings then attempt to login with those. If the user has _not_ set an RainLoop user/password in their personal settings, then fall back on trying to login using their NC credentials.

#### How it is _actually_ working in the current code
If this option is selected, then the app config `rainloop-autologin` is set to 1 in the database. If `rainloop-autologin` is set to 1, then RainLoop will [attempt to login using the user's NC credentials](https://github.com/pierre-alain-b/rainloop-nextcloud/blob/master/rainloop/lib/Controller/PageController.php#L80), but **does not** fall back to trying to use any credentials set by the user in their personal settings. Effectively, with this option set, the only way to auto-login to RainLoop is with the user's NC credentials.

### Automatically login with Nextcloud user email credentials or user defined credentials

#### What I think this is _supposed_ to mean
Attempt to auto-login to RainLoop using any credentials set by the user in their personal settings.

#### How it is _actually_ working in the current code
The code currently _always_ attempts to auto-login to RainLoop using credentials the user may or may not have set in their personal settings. Effectively this option does nothing different than the first option.

### Suggestion
Maybe we just want two options:
* "Automatically attempt to login using credentials set in your personal settings, else manually login.
* "Automatically attempt to login using your NC credentials, else manually login.

**Comment by Antoine26220** [comment]
The option "Try to determine user domain" and nothing in default domain works too!

**Comment by nkinkade** [comment]
@Antoine26220: Excellent, the way it is currently behaving makes sense to me and is logical, then. Glad this is working for you now.

**Comment by Antoine26220** [comment]
Yes it's great but all this options are unclear as possible!!!

**Comment by pierre-alain-b** [comment]
> Yes it's great but all this options are unclear as possible!!!

Well, me and the other contributors did our best :-(

**Comment by nkinkade** [comment]
@pierre-alain-b: What do you think of my comments/suggestions above?

**Comment by pierre-alain-b** [comment]
Just to clarify what the functions did at some point in the past (or at least were supposed to do) if I understood everything correctly (it was the topic of a few merge requests a few years ago).
1) => exactly as you said
2) and 3) were tweaked because it was needed in some cases to use the user account and in some other cases the email associated with the account.
At some point in the past, it was needed because some users were using LDAP and they had to use one or the other.

Now I concur with your idea that 2 could be enough if the code is in fact not separating both and if in fact it does not fallback to the user set credentials.

The labels of the options shall be written for administrators: so what about this?
- "Automatically attempt to login using credentials set in the users personal settings, else manually login."
- "Automatically attempt to login using the users nextcloud credentials, else manually login."

Maybe we shall precise if the nextcloud credentials are the username of the email attached to the user account.

**Comment by nkinkade** [comment]
Ah, thank you for that clarification. That helps. Now I understand what the last two options were supposed to mean and how they differed. Looking at the old app.php, it seems that [the logic for option 3 exists in the current v6.x release of this app](https://github.com/pierre-alain-b/rainloop-nextcloud/blob/64db6d15701967778e6dcb92776e6e9e28a03ed2/rainloop/app.php#L41), but is not carried forward in the App Framework change for v7.x. This was probably an oversight on my part, not understanding what the `rainloop-autologin-with-email` option was doing or meant.

Shall I port that old functionality forward? It seems like I probably should if people were using it before, they likely still are. I'm putting together another PR with some other small fixes and enhancements. I can re-add this functionality in that PR. Sound good?

**Comment by pierre-alain-b** [comment]
Well I agree I do not find 3 options in the code but only 2 in spite of the options offered to the users :-( I like the concept to allow to choose between the login or the mail. I think this can help many users.

Would you agree with 3 options:
    "Automatically attempt to login using credentials set in the users personal settings, else manually login."
    "Automatically attempt to login using the users Nextcloud credentials (username and password), else manually login."
    "Automatically attempt to login using the users Nextcloud credentials (email and password), else manually login."

?

**Comment by pierre-alain-b** [comment]
Sorry we commented at the same time.
Yes I agree the third option would be good if backported.

In fact I was trying this for PageController.php, not committed because test in progress:

```
                        $sUser = \OC::$server->getUserSession()->getUser()->getUID();
			$sUserEmail = \OC::$server->getUserSession()->getUser()->getEmailAddress();

			if ($this->config->getAppValue('rainloop', 'rainloop-autologin', false)) {
				$sEmail = $sUser;
				$sEncodedPassword = $this->session['rainloop-autologin-password'];
			} else if ($this->config->getAppValue('rainloop', 'rainloop-autologin-with-email', false)) {
				$sEmail = $sUserEmail;
				$sEncodedPassword = $this->session['rainloop-autologin-password'];				
			}	
			else {
				$sEmail = $this->config->getUserValue($sUser, 'rainloop', 'rainloop-email', '');
				$sEncodedPassword = $this->config->getUserValue($sUser, 'rainloop', 'rainloop-password', '');
			}
```

**Comment by pierre-alain-b** [comment]
Not working with the above code. Investigating.

**Comment by pierre-alain-b** [comment]
@nkinkade  and here you have the default behaviour to honour the individual email of the user
https://github.com/pierre-alain-b/rainloop-nextcloud/blob/64db6d15701967778e6dcb92776e6e9e28a03ed2/rainloop/app.php#L54
unless I am mistaken...

**Comment by nkinkade** [comment]
@pierre-alain-b: That all looks right. So to be sure we don't duplicate work, are you going to port forward those changes, or shall I add it to the small PR I'm already working on?

**Comment by pierre-alain-b** [comment]
I do not get what fail in my above code... if you have an idea...

**Comment by pierre-alain-b** [comment]
If you are kind enough to put everything in your PR, this would be wonderful! But my test of the option 3 ("with email") is not conclusive. But it is late for me to debug effectively!

**Comment by nkinkade** [comment]
No problem at all. I'll go ahead port forward the old behavior for auto-login to the new PageController code. Thanks!

**Comment by piti-diablotin** [comment]
Sorry for the late reply.I have been very busy. I indeed implemented the options 2 and 3.
And both are needed so your work is worth it.

Just to clarify (hopefully) the situation I got, I have on my NC server users with an email managed by my server and some other users with their own email. 
For those my server handle, using NC username/password worked somehow because I allowed the authentication on postfix with the same credentials but the problem was rainloop was using the wrong email which was username@domain and not the real email of the user. That is why I need to really use the email.

Now options 2 and 3 fall back to the user defined credentials if there defined so the user is in control of its own email if wanted. That was also mentioned in a previous issue.

If I can be of any help, let me know but I may not be the fastest right now and I don't know yet the new version 7.

Cheers

**Comment by piti-diablotin** [comment]
> This was probably an oversight on my part, not understanding what the `rainloop-autologin-with-email` option was doing or meant.

This was to implement option 3. It was meant to differentiate the username/password (option 2 ) `rainloop-autologin` from email/password (option 3) named `rainloop-autologin-with-email`...

My lack of knowledge of NC made me do this. Otherwise an `enum` would be nice but I don't know how to deal with that in NC DB.

**Comment by nkinkade** [comment]
@pierre-alain-b: https://github.com/pierre-alain-b/rainloop-nextcloud/pull/181

**Comment by Antoine26220** [comment]
> 
> 
> > Yes it's great but all this options are unclear as possible!!!
> 
> Well, me and the other contributors did our best :-(

Sorry my formulation was inappropriate. I didn't want to be mean...

**Comment by pierre-alain-b** [comment]
@Antoine26220  no worries! I did not take it personnally :-)
I've released 7.0-beta-6. @Antoine26220 would be excellent if you could test if it works as expected.

@others, I am bit puzzled because if option 1 works just seamlessly, I cannot get options 2 and 3 to work on my test instance. I've always used option 1 only. Where is the password found for options 2 and 3? The Nextcloud password is only stored as a hash but not clear text I presume, so it cannot be used to unlock an email account? Where is the trick?

@nkinkade, shouldn't we add rainloop-autogin-with-email here as well? 
```
		// Only store the user's password in the current session if they have
		// enabled auto-login using NC credentials.
		if ($config->getAppValue('rainloop', 'rainloop-autologin')) {
			$session['rainloop-autologin-password'] = $sEncodedPassword;
		}
```

**Comment by piti-diablotin** [comment]
@pierre-alain-b Actually, I have always wondered how the password way stored ! Because for obvious security reason It is not possible to store the clear password.
In previous version encoded password was stored in `'rainloop-autologin-password'` and I copied this for option 3 since my config uses the same password as for NC.
But I don't know how this variable is set however...

**Comment by Antoine26220** [comment]
> 
> 
> @Antoine26220 no worries! I did not take it personnally :-)
> I've released 7.0-beta-6. @Antoine26220 would be excellent if you could test if it works as expected.
> 
> @Others, I am bit puzzled because if option 1 works just seamlessly, I cannot get options 2 and 3 to work on my test instance. I've always used option 1 only. Where is the password found for options 2 and 3? The Nextcloud password is only stored as a hash but not clear text I presume, so it cannot be used to unlock an email account? Where is the trick?
> 
> @nkinkade, shouldn't we add rainloop-autogin-with-email here as well?
> 
> ```
> 		// Only store the user's password in the current session if they have
> 		// enabled auto-login using NC credentials.
> 		if ($config->getAppValue('rainloop', 'rainloop-autologin')) {
> 			$session['rainloop-autologin-password'] = $sEncodedPassword;
> 		}
> ```

I just installed it and i don't see any difference.
Again the only way to get autolgin to work is with long login, default domain set and using nextcloud credentials and not email.
I don't understand how the credentials are "made" by rainloop/nextcloud and what is send to the mail server.
What i understand is when i use the config descride above, my username is combine with the default domain ans this combination is sent to the mail server with the password. This is ok and it's works.

But when i want to use my nextcloud email with long login and no default domain the login fails...

It's ok for me, this config works but i feel something not user friendly in all these options... Perhaps it's come from the mail server configuration?

**Comment by piti-diablotin** [comment]
@Antoine26220 Maybe I missed the point but is the mail domain the same as the NC domain ?
On my config, with NC18 and rainloop 6, my default domain is configured and users with random emails can autologin.

Could you make a summary of what is working with just rainloop (forget about NC). Meaning default domain or not, mail with same domain or not, short or long credential, etc ... I am getting confused.

Once this is clear, I think we can figure out what should the rainloop NC app provide to  rainloop and thus what is the correct flow.

**Comment by Antoine26220** [comment]
My mail server and nextcloud is in the same domain and the same server.
The only config that works is what i said above:
on rainloop admin panel:
long login (short login uncheck)
default domain set on my domain (the same of nextcloud and mail server mail name)
and in nextcloud administration settings i set :
"Attempt to automatically login users with their Nextcloud username and password, or user-defined credentials, if set. "

I tried to change my server address from localhost to the fqdn name of my server and it's the same behavior.

I hope it's more clear :)

**Comment by piti-diablotin** [comment]
Is it with the last beta version ? 
If you use long login, you should select the third option: login with email/password and not username/password except maybe if the string before the @ of the email is the same as the username of NC?
Ex : username `toto` with `email my.toto@domain` cannot login with `toto`
username `toto` with email `toto@domain` and default domain set to `domain` shall login with `toto`

Can you specify what is the postfix/dovecot/.. auth mechanism and if LDAP, the kind of filter you use ?

**Comment by pierre-alain-b** [comment]
Just to clarify a little bit:
- option 1: the login and password are set by the user and that's it
- option 2 : the login sent to Rainloop is the username of the user in Nextcloud and from there it is to Rainloop to decide what to do with it! In that case, it seems normal to me that a default domain has to be set (or a wildcard domain used) => I guess Rainloop just sends the username and password to the mail server to get access
- option 3 : the login sent to Rainloop is the email address and in that case Rainloop should auto-detect which domain shall be used (just like when you manually enter that very same email address in the login box) => I guess Rainloop either sends the full email address or just the part before @ (short login ticked)

So for me, it is already good if it works like you say @Antoine26220. I guess that it should work with email as well if @nkinkade confirms that there is a fix needed for the segment below that does take into account option 3 (rainloop-autologin-with-email):

```
		// Only store the user's password in the current session if they have
		// enabled auto-login using NC credentials.
		if ($config->getAppValue('rainloop', 'rainloop-autologin')) {
			$session['rainloop-autologin-password'] = $sEncodedPassword;
		}
```

Now there is still the password origin mystery in options 2 and 3...

**Comment by Antoine26220** [comment]
@piti-diablotin dovecot is configure with auth_mechanisms = plain login and sasl for postfix.
I don't use ldap, i have only two users :)

@pierre-alain-b option 3 doesn't work with my config while my server seems to want the complete mail address. I think it would be simpler than setting option 2 with default domain

**Comment by pierre-alain-b** [comment]
See beta-7, I am pretty positive option 3 will work now.

I've just tested successfully the 3 options so I think we are good to go!

**Comment by Antoine26220** [comment]
It's seems to work :D 

With option 3 and no default domain.

**Comment by pierre-alain-b** [comment]
Great!

**Comment by nkinkade** [comment]
@pierre-alain-b, and everyone. Sorry for my late reply. I was not working yesterday, and was on kid duty all day and didn't have a chance to look at any of this until right now. :)

@pierre-alain-b: I see that you already fixed the error of not checking for both `rainloop-autologin` **and** `rainloop-autologin-with-email`, thank you for finding and fixing that.

I have the same mail setup as @piti-diablotin: Dovecot with plain login and sasl for Postfix, and thing work fine for me with short login. I don't know, but I imagine that login options/combinations with RainLoop NC app and RainLoop email app may be variable for users, since auth mechanisms in the backend mail (IMAP and SNMP) will be variable. I think if we can make clear assertions about what the Nextcloud RainLoop app sends to RainLoop, then that is about the best we can do. We don't have control of what the upstream RainLoop app does with those credentials, nor how the backed mail systems handle authentication and what they expect.  I don't personally see it as a requirement that this NC app document what all the various RainLoop admin configurations are and mean. [The upstream app should document those things](https://www.rainloop.net/docs/), and this app should point to that documentation. Duplication documentation is probably not the right thing, as we don't control that app and the onus would then be on us to keep it in sync with the upstream app.

Regarding the password origin for options 2 and 3. Previously it was stored in the database under a user setting named `rainloop-autologin-password`, as @pierre-alain-b mentioned. Now it is stored as an ephemeral browser session variable. When the app loads, [some hooks are registered](https://github.com/pierre-alain-b/rainloop-nextcloud/blob/master/rainloop/appinfo/app.php#L14), one of which is [the NC `'login` hook](https://github.com/pierre-alain-b/rainloop-nextcloud/blob/master/rainloop/lib/Util/RainLoopHelper.php#L25). [This function assigned to this hook](https://github.com/pierre-alain-b/rainloop-nextcloud/blob/master/rainloop/lib/Util/RainLoopHelper.php#L215) stores the user's login password in the session.

Regarding all of this generally, when the session ends the data vanishes (assuming PHP garbage-collects the session file stored on the server's disk). And I don't know if this is true for everyone, but when I looked at session files in `/var/lib/php/session` (that directory may vary depending on your PHP config) on the server, all the files have only one variable named `encrypted_session_data`, and then encrypted data. I believe this is Nextcloud doing this, not PHP, though I haven't 100% verified this. I see this change as a little bit better than storing the password in the database. As far as I understand it, encrypting the password (whether in the database or in the session) is more or less useless, though I may not be thinking clearly about it. Encrypted data is only useful when the encryption key is unknown to 3rd parties. In this case, the encryption algorithm and salt are public information; it's right in the opensource code. If an attacker got hold of the data from the database, or was able to get the unencrypted session data, then they can just use the same process that the [decodetPassword()](https://github.com/pierre-alain-b/rainloop-nextcloud/blob/master/rainloop/lib/Util/RainLoopHelper.php#L193) function uses to get the cleartext password. A hash likely the only secure way of storing it, but we can't work with a hash, because once hashed we have no way of working with it (that being the point of a hash). Additionally, what I found was that on my system the password was only base64 encoded, not encrypted, because my server doesn't have the `openssl` module loaded for PHP. In any case, I think storing the user's password only in the session is a bit safer and NC seems to encrypt that data on the disk.

Is there anything pending that I need to do or answer or comment on here? Sorry for this long rambling post.

**Comment by pierre-alain-b** [comment]
Thank you for the clarification, for me all is pretty clear!
