### ISSUE TITLE
[feature request] Status / Inbox in Dashboard

### ISSUE THREAD

**Issue by dermitdemdino** [pierre-alain-b/rainloop-nextcloud#255]
The "Nextcloud Mail App" has this, it would be nice if I had this with Rainloop too.
![Bildschirmfoto von 2021-11-13 15-52-44](https://user-images.githubusercontent.com/6813869/141648338-001431b7-938c-436b-8dc6-23141a2ae202.png)

**Comment by pierre-alain-b** [comment]
Unfortunately this is not planned given the loose way Rainloop is interconnected with Nextcloud.

**Comment by janban-outlook** [comment]
As a workaround, you can activate the mail app next to Rainloop. Then you have at least the dashboard widget to see which unread messages you have. 

I am using the same approach for Deck and Tasks, where I prefer to use Deck to maintain my tasks, but having the Tasks widget on the dashboard because it gives more information.
