### ISSUE TITLE
Set property in File libraries/MailSo/Smtp/SmtpClient.php

### ISSUE THREAD

**Issue by serve-id** [pierre-alain-b/rainloop-nextcloud#265]
hello together, 
in some Installations / Setups it is necessary to set the property :
$__USE_SINGLE_LINE_AUTH_PLAIN_COMMAND = 
from false to true. 

Can you make this property visible in the context menu of the Rainloop settings (within Nextcloud), so that you don't have to manually change the file on every update? 

Best Greetings

**Comment by pierre-alain-b** [comment]
Can you tell me more on what this option does? I am surprised this is hard coded and not proposed as an option in Rainloop settings. It would be a better place to have this managed in the options of Rainloop itself rather than in the integration of Rainloop in Nextcloud.
Have you had a try with Snappy to see if this was placed as an option in Snappy webmail (a fork of Rainloop) ?

**Comment by the-djmaze** [comment]
> Have you had a try with Snappy to see if this was placed as an option in Snappy webmail (a fork of Rainloop) ?

That option is gone in SnappyMail. It's always single line according to RFC 4616

**Comment by pierre-alain-b** [comment]
I recommend that you take a loot at snappymail being ported to Nextcloud. Snappymail is maintained unlike Rainloop that seems not to be anymore. https://github.com/the-djmaze/snappymail/issues/96
