### ISSUE TITLE
Use images from the Nextcloud contacts list

### ISSUE THREAD

**Issue by VisioFX** [pierre-alain-b/rainloop-nextcloud#30]
Change Request: Use images from list of Nextcloud contacts.
Only use Gravatar images when no corresponding user is found in the Nextcloud contacts list.

**Comment by pierre-alain-b** [comment]
This is a good idea but is not totally easy. If someone would like to experiment in this direction, it would be great!

**Comment by HibGut** [comment]
@pierre-alain-b , are you involved in original Rainloop development? Or are you "only" doing the Nextcloud integration?

Do things like attaching files from Nextcloud, adding events from email invitations to the Nextcloud calendar, using contact avatars from Nextcloud require changes in the Rainloop core code or would that be part of the integration app?

**Comment by pierre-alain-b** [comment]
To be honest, I never committed a single patch to the Rainloop code base and I do not plan to start doing it (not that I am not interested in Rainloop but I will just not find the time). In fact, when owncloud was forked into nextcloud, I contacted the Rainloop team that was packaging the app for owncloud and enquired wether they would do to the same for Nextcloud. As I got no reply, I decided to do it myself and offer it to everyone through the Nextcloud app repository. And now I continue to try to help the users out there, package new versions of Rainloop when they are published, and I of course accept the help of anyone to improve the integration.

I will continue to do to it for the community but my involvement in Rainloop is, as you can see, minor. Luckily, Rainloop is pretty stable in my personal use.

I am therefore mainly a package maintainer rather than a core developer for this project.

**Comment by pierre-alain-b** [comment]
I suggest that you look at the work here on Snappymail: https://github.com/the-djmaze/snappymail/issues/96
