### ISSUE TITLE
Security - storage of credentials

### ISSUE THREAD

**Issue by pierre-alain-b** [pierre-alain-b/rainloop-nextcloud#34]
Issue seen here https://github.com/RainLoop/rainloop-webmail/issues/1082
does apply to the nextcloud plugin as well!

**Comment by muppeth** [comment]
What stands in the way of merging changes from https://github.com/RainLoop/rainloop-webmail/commit/6f4b7b8156104dc5172910a93191bc39a34ee1e6
Have you tried it yourself? I'm thinking of running those on my instance, but of ocurse I would like to avoid having to maintain my own version. 

As it is currently autologin should be generally disabled and now allowed, so changing it by merging this commit will be an improvement. Yes it will force users to type their password once again but only one time. I think its something to consider because most of the people hosting their nextcloud/owncloud are not aware of the issue.

**Comment by pierre-alain-b** [comment]
I will have a look at it. But I would rather wait for the next official Rainloop release to have this included in a release of the plugin.

**Comment by pierre-alain-b** [comment]
That said, feel free to give it a go. If you report that this works well, I will be even more eager to test and do it as well in the version published on the nextcloud apps repo.

**Comment by pierre-alain-b** [comment]
I've just tested the commit and it seems to work fine. I will take it then and I will publish a newer version for the Nextcloud apps repository.
