### ISSUE TITLE
Contact config automated

### ISSUE THREAD

**Issue by sachaz** [pierre-alain-b/rainloop-nextcloud#52]
How can I have for all my users as default preference for contacts as cardav URL: https://mysite/remote.php/dav
and as user the same user as nextcloud/rainloop/ldap ?

**Comment by DJCrashdummy** [comment]
well, a good question...
i managed to set all general/default and "hidden" preferences with manipulating `path/to/nextcloud/data/rainloop-storage/_data_/_default_/configs/application.ini` except the setting for desktop- & sound-notification has to be set per user in the file `path/to/nextcloud/data/rainloop-storage/_data_/_default_/storage/cfg/xx/user@domain.tld/settings`.
even the identities and signatures can be set via `path/to/nextcloud/data/rainloop-storage/_data_/_default_/storage/cfg/xx/user@domain.tld/identities`, but the cryptical strings at `path/to/nextcloud/data/rainloop-storage/_data_/_default_/storage/cfg/xx/user@domain.tld/contacts_sync` didn't get me further... :confused: 

i'm afraid this can't be set, since you also have to know the name/url of the users address-book and his password...
but if there are any ideas how to achieve this (at least partly - e.g. except the password), i'm all ears! :wink:

**Comment by pierre-alain-b** [comment]
I suggest that you look at the work here on Snappymail: https://github.com/the-djmaze/snappymail/issues/96
