### ISSUE TITLE
Default username / password Doesn't work...

### ISSUE THREAD

**Issue by P4pa-Joe** [pierre-alain-b/rainloop-nextcloud#53]
Hello,

I just install Rainloop for nextcloud. When I try to login to admin session in "Additionnal settings" with user & pass : admin / 12345, I receive an "Authentication failed".

**Comment by ohmer1** [comment]
I guess you tried to login with the login form you get when you choose the rainloop app. This is not the right one. I know, I did the same error! You must look at the additionnel nextcloud settings and clic on the link to get the rainloop admin login form.

**Comment by pierre-alain-b** [comment]
HI, I agree with ohmer1 that it looks this! Let us know if it still doesn't work.

**Comment by P4pa-Joe** [comment]
Thanks for reply.
Like I said in my first message, I try to log in "Additionnal settings" > "Go to RainLoop Webmail admin panel"... and it doesn't work.

**Comment by pierre-alain-b** [comment]
Are you sure a previous version on Rainloop was not installed earlier in the life of the NC instance and the default password changed?

You can open this file: `/path/to/nextcloud/data/rainloop-storage/_data_/_default_/configs/application.ini` and have a look at the "Login and password" section:

```
; Login and password for web admin panel
admin_login = "admin"
admin_password = "12345"
```

Don't you see another login name and maybe a hashed password instead of the default one?
