### ISSUE TITLE
nextcloud groups as possible recipients

### ISSUE THREAD

**Issue by tim-krehan** [pierre-alain-b/rainloop-nextcloud#96]
hello everyone! I hope, this has not allread been requested.
The request is, that (as users currently are) all the groups are also suggested, while typing in the "TO:"-field.
Is there anything in work currently?

**Comment by pierre-alain-b** [comment]
Hi, this is not in work but could be useful yes. I have tagged this a possible enhancement.

**Comment by jf34000** [comment]
Hi,
3 years later I know, but it seems this enhancement is still "pending"
In my company everybody prefer RainLoop rather than the default Nextcloud "Mail" app.
But we are using every day the"groups" to send emails, so we are "stucked" with "Mail" (and it's sad :)
So +1 for groups as possible recipients !

**Comment by pierre-alain-b** [comment]
I suggest that you look at the work here on Snappymail: https://github.com/the-djmaze/snappymail/issues/96
